import h5py as h5
import numpy as np


def load_probes(probe_ids, f):
    """
    Load probe data from an HDF5 file.

    Parameters
    ----------
    probe_ids: list
        A list of probe ids/keys as strings.

    f: string
        Name of an HDF5 containing data from probes stored in the ``probes''
        list.

    Returns
    -------
    A dictionary mapping probe keys to data.
    """

    f = h5py.File(f, 'r')


def merge_probes(probe_map, infile, outfile):
    """
    When we split up ensemble arrays (as we sometimes have to do in order to
    increase the number of independently simulatable components in a network),
    any probes of the split ensemble arrays are also split. These probe splits
    are tracked using a dictionary mapping each original probe to a list of
    the corresponding probes in the split-up network. This function uses this
    probe map to take results from a simulation of the split-up network, merge
    them into single arrays (as if the network had never been split), and save
    the results.

    probe_map: dict
        Maps from probes (or probe ids) in the original network to a list of
        corresponding probes (or probe ids) in the split-up network.

    infile: h5.File (or name of file)
        H5 file containing data generated by the split up network.

    outfile: h5.File (or name of file)
        H5 file containing data from the input file, but organized as if it had
        been generated by the non-split network.
    """

    if isinstance(infile, str):
        infile = h5.File(infile, 'r')

    if isinstance(outfile, str):
        outfile = h5.File(outfile, 'w')

    new_probe_ids = list(infile)

    for probe_id, p_ids in probe_map:
        outfile[probe_id] = np.concatenate([infile[i] for i in p_ids])
        outfile[probe_id].attrs['name'] = infile[p_ids[0]].attrs['name']
        new_probe_ids = [i for i in new_probe_ids if i not in p_ids]

    for p_id in new_probe_ids:
        outfile[p_id] = infile[p_id]
        outfile[p_id].attrs['name'] = infile[p_id].attrs['name']
